apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-monitor
  template:
    metadata:
      labels:
        app: system-monitor
    spec:
      containers:
        - name: monitor
          image: kavanabt6/local-hybrid-cloud-monitor:v2
          imagePullPolicy: Always
