apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitor

spec:
  replicas: 1

  selector:
    matchLabels:
      app: system-monitor

  template:
    metadata:
      labels:
        app: system-monitor

    spec:
      containers:
        - name: monitor
          image: kavanabt6/local-hybrid-cloud-monitor:3b66487
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          volumeMounts:
            - name: monitor-logs
              mountPath: /app/logs

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15

      volumes:
        - name: monitor-logs
          persistentVolumeClaim:
            claimName: system-monitor-logs

