name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Check project
        run: |
          cd ~/local-hybrid-cloud-gitops
          pwd
          grep "image:" k8s/deployment.yaml

      - name: Set image tag
        id: vars
        run: |
          TAG="${{ github.event.workflow_run.head_sha }}"
          echo "TAG=${TAG:0:7}" >> "$GITHUB_OUTPUT"

      - name: Update Kubernetes image
        run: |
          cd ~/local-hybrid-cloud-gitops
          sed -i "s|image: kavanabt6/local-hybrid-cloud-monitor:.*|image: kavanabt6/local-hybrid-cloud-monitor:${{ steps.vars.outputs.TAG }}|" k8s/deployment.yaml
          grep "image:" k8s/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          cd ~/local-hybrid-cloud-gitops
          kubectl apply -f k8s/deployment.yaml

      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/system-monitor --timeout=300s

      - name: Verify deployment
        run: |
          kubectl get pods -l app=system-monitor
          kubectl get deployment system-monitor -o=jsonpath='{.spec.template.spec.containers[0].image}'
          echo

